# Generated by Django 6.0.3 on 2026-03-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200)),
                ('place_desc', models.CharField(max_length=200)),
                ('estimated_cost', models.IntegerField()),
            ],
        ),
    ]
