# Generated by Django 6.0.3 on 2026-03-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT36fqQUPeXvmxYZlOAzqiIFNwMOcXwRQHBgw&s', max_length=500),
        ),
    ]
