# Generated by Django 6.0.3 on 2026-03-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_place_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_desc',
            field=models.CharField(max_length=500),
        ),
    ]
