# Generated by Django 6.0.3 on 2026-03-25 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_place_latitude_place_longitude_place_region_trip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='region',
            field=models.CharField(choices=[('TERAI', 'Terai'), ('HILLS', 'Hills'), ('HIMALAYA', 'Himalaya')], db_index=True, default='HILLS', max_length=20),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['place', '-created_at'], name='travel_revi_place_i_033147_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user', '-created_at'], name='travel_trip_user_id_dfc4f8_idx'),
        ),
    ]
